# Environment configuration for the adaptive lookback task.
min_lookback: 5
max_lookback: 90
default_lookback: 30
discrete_actions: true
reward_weights:
  signal_strength: 1.0
  stability: 0.6
  regularization: 0.15
episode_length: 180
random_start: true
include_strength_feature: true

leadlag:
  method: ccf_at_lag
  lookback: 30
  update_freq: 1
  use_parallel: false
  num_cpus: 4
  show_progress: false
  Scaling_Method: mean-centering
  ccf_at_lag:
    lag: 1
    correlation_method: pearson
    quantiles: 4
