# Hyper-parameters for the PPO agent.
policy: MlpPolicy
learning_rate: 3.0e-4
n_steps: 2048
batch_size: 64
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
use_sde: false
tensorboard_log: null
policy_kwargs: {}
use_lstm: false
